<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Extension points for CICD plugins. Reference this from plugin projects.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Cicd.Contracts/Cicd.Contracts.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>
</Project>
