<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <ArtifactsRoot>$(RepoRoot)artifacts/</ArtifactsRoot>
    <PluginsOutputRoot>$(ArtifactsRoot)plugins/</PluginsOutputRoot>
    <AnalysisLevel>latest</AnalysisLevel>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
