<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);xUnit1004</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Cicd.Core/Cicd.Core.csproj" />
    <ProjectReference Include="../../plugins/Cicd.Plugins.CommandLine/Cicd.Plugins.CommandLine.csproj" />
    <ProjectReference Include="../../plugins/Cicd.Plugins.GitHub/Cicd.Plugins.GitHub.csproj" />
  </ItemGroup>
</Project>
