// <auto-generated />
using System;
using Cicd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cicd.Data.Migrations
{
    [DbContext(typeof(PostgresCicdDbContext))]
    [Migration("20260917004306_AddSettingsAndProtectVcsRootProperties")]
    partial class AddSettingsAndProtectVcsRootProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cicd.Core.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Authorized")
                        .HasColumnType("boolean")
                        .HasColumnName("authorized");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("capabilities")
                        .HasAnnotation("Cicd:Json", true);

                    b.Property<Guid?>("CurrentBuildId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_build_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_agents_name");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Cicd.Core.Entities.Build", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("branch");

                    b.Property<Guid>("BuildConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("build_configuration_id");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_requested");

                    b.Property<string>("CheckoutRef")
                        .HasColumnType("text")
                        .HasColumnName("checkout_ref");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("LogLineCount")
                        .HasColumnType("bigint")
                        .HasColumnName("log_line_count");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<Guid?>("PullRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pull_request_id");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<string>("Revision")
                        .HasColumnType("text")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StatusText")
                        .HasColumnType("text")
                        .HasColumnName("status_text");

                    b.Property<string>("StepRuns")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("step_runs")
                        .HasAnnotation("Cicd:Json", true);

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id")
                        .HasName("pk_builds");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_builds_agent_id");

                    b.HasIndex("PullRequestId")
                        .HasDatabaseName("ix_builds_pull_request_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_builds_status");

                    b.HasIndex("BuildConfigurationId", "QueuedAt")
                        .HasDatabaseName("ix_builds_build_configuration_id_queued_at");

                    b.ToTable("builds", (string)null);
                });

            modelBuilder.Entity("Cicd.Core.Entities.BuildArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("uuid")
                        .HasColumnName("build_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.HasKey("Id")
                        .HasName("pk_build_artifacts");

                    b.HasIndex("BuildId")
                        .HasDatabaseName("ix_build_artifacts_build_id");

                    b.ToTable("build_artifacts", (string)null);
                });

            modelBuilder.Entity("Cicd.Core.Entities.BuildConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentRequirements")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("agent_requirements")
                        .HasAnnotation("Cicd:Json", true);

                    b.Property<string>("ArtifactPaths")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("artifact_paths")
                        .HasAnnotation("Cicd:Json", true);

                    b.Property<int>("BuildCounter")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("build_counter");

                    b.Property<string>("BuildNumberFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("build_number_format");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters")
                        .HasAnnotation("Cicd:Json", true);

                    b.Property<bool>("Paused")
                        .HasColumnType("boolean")
                        .HasColumnName("paused");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PullRequests")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("pull_requests")
                        .HasAnnotation("Cicd:Json", true);

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("steps")
                        .HasAnnotation("Cicd:Json", true);

                    b.Property<string>("Triggers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("triggers")
                        .HasAnnotation("Cicd:Json", true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VcsRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("vcs_root_id");

                    b.HasKey("Id")
                        .HasName("pk_build_configurations");

                    b.HasIndex("VcsRootId")
                        .HasDatabaseName("ix_build_configurations_vcs_root_id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_build_configurations_project_id_name");

                    b.ToTable("build_configurations", (string)null);
                });

            modelBuilder.Entity("Cicd.Core.Entities.BuildLogLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BuildId")
                        .HasColumnType("uuid")
                        .HasColumnName("build_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<int?>("StepIndex")
                        .HasColumnType("integer")
                        .HasColumnName("step_index");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_build_log_lines");

                    b.HasIndex("BuildId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_build_log_lines_build_id_sequence");

                    b.ToTable("build_log_lines", (string)null);
                });

            modelBuilder.Entity("Cicd.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_name");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_projects_parent_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Cicd.Core.Entities.PullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("CheckoutRef")
                        .HasColumnType("text")
                        .HasColumnName("checkout_ref");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("head_sha");

                    b.Property<string>("LastBuiltShaByConfiguration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("last_built_sha_by_configuration")
                        .HasAnnotation("Cicd:Json", true);

                    b.Property<long>("Number")
                        .HasColumnType("bigint")
                        .HasColumnName("number");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_branch");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_branch");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("VcsRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("vcs_root_id");

                    b.HasKey("Id")
                        .HasName("pk_pull_requests");

                    b.HasIndex("VcsRootId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_pull_requests_vcs_root_id_number");

                    b.ToTable("pull_requests", (string)null);
                });

            modelBuilder.Entity("Cicd.Core.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Cicd.Core.Entities.TriggerStateEntry", b =>
                {
                    b.Property<Guid>("BuildConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("build_configuration_id");

                    b.Property<int>("TriggerIndex")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_index");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("BuildConfigurationId", "TriggerIndex", "Key")
                        .HasName("pk_trigger_state");

                    b.ToTable("trigger_state", (string)null);
                });

            modelBuilder.Entity("Cicd.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_issuer_subject");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Cicd.Core.Entities.VcsRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_branch");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_vcs_roots");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_vcs_roots_project_id");

                    b.ToTable("vcs_roots", (string)null);
                });

            modelBuilder.Entity("Cicd.Core.Entities.Build", b =>
                {
                    b.HasOne("Cicd.Core.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_builds_agents_agent_id");

                    b.HasOne("Cicd.Core.Entities.BuildConfiguration", "BuildConfiguration")
                        .WithMany()
                        .HasForeignKey("BuildConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_builds_build_configurations_build_configuration_id");

                    b.HasOne("Cicd.Core.Entities.PullRequest", "PullRequest")
                        .WithMany()
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_builds_pull_requests_pull_request_id");

                    b.Navigation("Agent");

                    b.Navigation("BuildConfiguration");

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("Cicd.Core.Entities.BuildArtifact", b =>
                {
                    b.HasOne("Cicd.Core.Entities.Build", null)
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_build_artifacts_builds_build_id");
                });

            modelBuilder.Entity("Cicd.Core.Entities.BuildConfiguration", b =>
                {
                    b.HasOne("Cicd.Core.Entities.Project", "Project")
                        .WithMany("BuildConfigurations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_build_configurations_projects_project_id");

                    b.HasOne("Cicd.Core.Entities.VcsRoot", "VcsRoot")
                        .WithMany()
                        .HasForeignKey("VcsRootId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_build_configurations_vcs_roots_vcs_root_id");

                    b.Navigation("Project");

                    b.Navigation("VcsRoot");
                });

            modelBuilder.Entity("Cicd.Core.Entities.BuildLogLine", b =>
                {
                    b.HasOne("Cicd.Core.Entities.Build", null)
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_build_log_lines_builds_build_id");
                });

            modelBuilder.Entity("Cicd.Core.Entities.Project", b =>
                {
                    b.HasOne("Cicd.Core.Entities.Project", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_projects_projects_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Cicd.Core.Entities.PullRequest", b =>
                {
                    b.HasOne("Cicd.Core.Entities.VcsRoot", "VcsRoot")
                        .WithMany()
                        .HasForeignKey("VcsRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pull_requests_vcs_roots_vcs_root_id");

                    b.Navigation("VcsRoot");
                });

            modelBuilder.Entity("Cicd.Core.Entities.VcsRoot", b =>
                {
                    b.HasOne("Cicd.Core.Entities.Project", "Project")
                        .WithMany("VcsRoots")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vcs_roots_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Cicd.Core.Entities.Project", b =>
                {
                    b.Navigation("BuildConfigurations");

                    b.Navigation("VcsRoots");
                });
#pragma warning restore 612, 618
        }
    }
}
